apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-gha-kubectl-apply
  namespace: service-account-ns
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: svc-gha-kubectl-apply-token
  namespace: service-account-ns
  annotations:
    kubernetes.io/service-account.name: "svc-gha-kubectl-apply"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: svc-gha-kubectl-apply-clusterrole
rules:
  - apiGroups: [""]
    resources:
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
