name: 'Prepare Docs Environment'
description: 'Ensure docs venv exists with necessary Python dependencies'

runs:
  using: "composite"

  steps:
    - name: Set up Python
      id: set_up_python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # SHA for version 5.6.0
      with:
        python-version: "3.12"

    - name: Get environment info
      id: env_info
      run: |
        run: |
          venv_dir=docs/$(make --directory=docs --no-print-directory print-venv-dir)
          python_reqs_file=docs/$(make --directory=docs --no-print-directory print-python-requirements-file)

          echo "venv_dir=$venv_dir" >> $GITHUB_OUTPUT

          # GitHub’s hashFiles isn’t available here, so use sha256sum
          echo "python_hash=$(sha256sum $python_reqs_file | cut -d ' ' -f1)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache docs venv
      id: cache-venv
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # SHA for version 4.2.4
      with:
        key: venv-docs-${{ runner.os }}-${{ steps.set_up_python.outputs.python-version }}-${{ steps.env_info.outputs.python_hash }}
        path: ${{ steps.env_info.outputs.venv_dir }}

    - name: Install dependencies according to requirements files
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: make --directory=docs venv
      shell: bash
