---
- name: Set service accounts file
  hosts: localhost
  gather_facts: false
  tags: always

  vars:
    service_accounts_file: "{{ playbook_dir }}/../../data/service_accounts.yaml"

  tasks:
    - name: Load service accounts from YAML (list)
      ansible.builtin.set_fact:
        service_accounts: "{{ lookup('file', service_accounts_file) | from_yaml }}"


- name: Create service accounts from data/service_accounts.yaml
  hosts: k3s_cluster
  become: true
  gather_facts: false
  tags: [create]
  vars:
    is_create: "{{ 'remove' not in ansible_run_tags }}"

  tasks:
    - name: Create account if `remove` tag is not passed
      when: is_create
      ansible.builtin.include_role:
        name: account_creator
      loop: "{{ hostvars['localhost']['service_accounts'] }}"
      loop_control:
        loop_var: acct
      vars:
        account: "{{ acct }}"


- name: Remove service accounts from data/service_accounts.yaml
  hosts: k3s_cluster
  become: true
  gather_facts: false
  tags: [remove]
  vars:
    is_remove: "{{ 'remove' in ansible_run_tags }}"

  tasks:
    - name: Remove service accounts if `remove` tag is passed
      when: is_remove
      ansible.builtin.include_role:
        name: account_remover
      loop: "{{ hostvars['localhost']['service_accounts'] }}"
      loop_control:
        loop_var: acct
      vars:
        account: "{{ acct }}"
