---
roles:
  # For setting up PostgreSQL database
  - name: geerlingguy.postgresql
    version: "4.0.1"

  # For installing self-hosted GitHub Actions runner
  - name: monolithprojects.github_actions_runner
    version: 436f45b0e0d5b69df82cf5414c2786e63f0d4fc0 # 1.27.0
    src: https://github.com/MonolithProjects/ansible-github_actions_runner

  # For installing kubectl
  - name: githubixx.kubectl
    src: https://github.com/githubixx/ansible-role-kubectl.git
    version: 45473959052c83b81f2a852306407c4222e47d0d # 26.0.0+1.35.1

collections:
  # For deploying K3s cluster
  - name: https://github.com/timothystewart6/k3s-ansible
    type: git
    version: 668d7fb896c226cde2960491a60b917db8a4bf7e # 1.30.2

  # Needed for timothystewart6/k3s-ansible
  - name: ansible.utils
    version: 6.0.2
  - name: community.general
    version: 11.2.1
  - name: ansible.posix
    version: 2.1.0
  - name: kubernetes.core
    version: 6.1.0
