site_name: Gohfert Cluster
site_author: Felix Seifert

repo_url: https://github.com/felix-seifert/gohfert-cluster
edit_uri: edit/main/docs/

docs_dir: ./content/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate

markdown_extensions:
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
      format: svg
      base_dir: ./content
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # yamllint disable-line rule:truthy
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - index.md
  - ADRs:
      - "01 -- Deploy K3s Through Ansible": adrs/01-deploy-k3s-through-ansible.md
      - "02 -- Use Makefiles for CI Commands": adrs/02-use-makefiles-for-ci-commands.md
  - Explanations:
      - Architecture: explanations/architecture.md
      - Certificates for TLS: explanations/ca-certs.md
      - cloud-init: explanations/cloud-init.md
      - DNS for Deployed K8s Services: explanations/dns-for-deployed-k8s-services.md
      - GitHub Actions Runners: explanations/gha-runners.md
      - K3s High Availability Cluster: explanations/k3s-high-availability-cluster.md
      - MAAS Provisioning Flow: explanations/provisioning-flow.md
      - SSH Into K3s Nodes: explanations/ssh-into-k3s-nodes.md
  - Guides:
      - Debug Network Discovery: guides/debug-network-discovery.md
      - Deploy Private GHA Runners: guides/deploy-private-gha-runners.md
      - Provision New Machine: guides/provision-new-machine.md
      - Reprovision Existing Machine: guides/reprovision-existing-machine.md
      - SSH Via Jumphost: guides/ssh-via-jumphost.md
  - References:
      - Certificates for TLS: references/ca-certs.md
      - Client Settings for MAAS: references/client-settings-for-maas.md
      - Machine Names: references/machine-names.md
      - Router Settings for MAAS: references/router-settings-for-maas.md
  - Requirements: requirements.md
