---
account: felix-seifert
# For security purposes, self-hosted runners are in this private repo and triggered via `repository_dispatch` events.
repo: gohfert-cluster-private-runners

github_pat: "{{ vault_github_pat }}"
gha_runner_user: gha-runner
gha_runner_name: maas-runner

gha_runner_version: "2.328.0"
