name: build-docs-image

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  build-image:
    name: Build and push docs image
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.image_details.outputs.image_name }}
      image_tag: ${{ steps.image_details.outputs.image_tag }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # SHA for version 5.0.0

      - name: Set up Python
        id: set_up_python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # SHA for version 5.6.0
        with:
          python-version: "3.12"

      - name: Get environment info
        id: env_info
        run: |
          venv_dir=docs/$(make --directory=docs --no-print-directory print-venv-dir)
          python_reqs_file=docs/$(make --directory=docs --no-print-directory print-python-requirements-file)

          echo "venv_dir=$venv_dir" >> $GITHUB_OUTPUT
          echo "python_reqs_file=$python_reqs_file" >> $GITHUB_OUTPUT

          # GitHub’s hashFiles isn’t available here, so use sha256sum
          echo "python_hash=$(sha256sum $python_reqs_file | cut -d ' ' -f1)" >> $GITHUB_OUTPUT

      - name: Cache venv
        id: cache-venv
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # SHA for version 4.2.4
        with:
          key: venv-docs-${{ runner.os }}-${{ steps.set_up_python.outputs.python-version }}-${{ steps.env_info.outputs.python_hash }}
          path: ${{ steps.env_info.outputs.venv_dir }}

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: make --directory=docs venv

      - name: Build static documentation pages
        run: make --directory=docs build-site

      - name: Build Docker image
        run: make --directory=docs build-image

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # SHA for version 3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to ghcr.io
        run: make --directory=docs push-image

      - name: Get Docker image details
        id: image_details
        run: |
          image_name=$(make --directory=docs --no-print-directory print-image-name)
          image_tag=$(make --directory=docs --no-print-directory print-image-tag)

          echo "image_name=$image_name" >> $GITHUB_OUTPUT
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT

  call-update-image-tag:
    name: Call workflow to update Docker image tag in Kubernetes manifests
    needs: build-image
    secrets: inherit
    uses: ./.github/workflows/update_docker_image_tag.yaml
    with:
      image: ${{ needs.build-image.outputs.image_name }}
      tag: ${{ needs.build-image.outputs.image_tag }}
      app: docs
