name: build-docs-image

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  build-image:
    name: Build and push docs image
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.image_details.outputs.image_name }}
      image_tag: ${{ steps.image_details.outputs.image_tag }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # SHA for version 5.0.0

      - name: Set up env with Python and dependencies
        uses: ./.github/actions/prepare-docs-env-composite-action

      - name: Build static documentation pages
        run: make --directory=docs build-site

      - name: Build Docker image
        run: make --directory=docs build-image

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # SHA for version 3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to ghcr.io
        run: make --directory=docs push-image

      - name: Get Docker image details
        id: image_details
        run: |
          image_name=$(make --directory=docs --no-print-directory print-image-name)
          image_tag=$(make --directory=docs --no-print-directory print-image-tag)

          echo "image_name=$image_name" >> $GITHUB_OUTPUT
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT

  call-update-image-tag:
    name: Call workflow to update Docker image tag in Kubernetes manifests
    needs: build-image
    secrets: inherit
    uses: ./.github/workflows/update_docker_image_tag.yaml
    with:
      image: ${{ needs.build-image.outputs.image_name }}
      tag: ${{ needs.build-image.outputs.image_tag }}
      app: docs
