name: kubernetes-apply-dispatch

on:
  push:
    branches:
      - main
    paths:
      - kubernetes/**

jobs:
  apply-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # SHA for version 5.0.0
        with:
          fetch-depth: 0

      - name: Get changed files in `kubernetes/` dir
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # SHA for version 47
        with:
          files: |
            kubernetes/**

      - name: Extract changed subdirs from changed files
        run: |
          changed_subdirs=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" \
            | grep '^kubernetes/' \
            | cut --delimiter '/' -f2 \
            | sort --unique \
            | paste --serial --delimiter "," -)

          echo "Changed subdirectories: $changed_subdirs"

          echo "CHANGED_SUBDIRS=$changed_subdirs" >> $GITHUB_ENV

      - name: Trigger Kubernetes manifest application
        uses: peter-evans/repository-dispatch@de78ac1a711fc6f29e77338f843065faf5335227 # Commit from 19 Sep 2025
        with:
          token: ${{ secrets.PAT_FOR_TRIGGERING_PRIVATE_WORKFLOWS }}
          repository: felix-seifert/gohfert-cluster-private-runners
          event-type: kubernetes-manifests-apply
          client-payload: '{"ref": "${{ github.ref }}", "changed_kubernetes_subdirs": "${{ env.CHANGED_SUBDIRS }}"}'
