name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Makefile Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # SHA for version 5.0.0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # SHA for version 5.6.0
        with:
          python-version: "3.12"
          cache: pip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # SHA for version 3.1.2
        with:
          terraform_version: "1.13.1"
          terraform_wrapper: false

      - name: Init Terraform
        run: make init

      - name: Set up venv with dependencies
        run: make venv

      - name: Run linting
        run: make lint
