name: Lint Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/**

jobs:
  lint-docs:
    name: Lint and build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Setup docs env with Python and dependencies
        uses: ./.github/actions/prepare-docs-env-composite-action

      - name: Run Markdown linting
        run: make --directory=docs lint

      - name: Build static documentation pages
        run: make --directory=docs build-site
