name: Lint Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - docs/**

jobs:
  lint-docs:
    name: Lint and build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup docs env with Python and dependencies
        uses: ./.github/actions/prepare-docs-env-composite-action

      - name: Run Markdown linting
        run: make --directory=docs lint

      - name: Build static documentation pages
        run: make --directory=docs build-site
