name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Makefile Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # SHA for version 5.0.0

      - name: Setup env with Python and Ansible dependencies
        uses: ./.github/actions/prepare-env-composite-action

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # SHA for version 3.1.2
        with:
          terraform_version: "1.13.1"
          terraform_wrapper: false

      - name: Init Terraform
        run: make init

      - name: Run linting
        run: make lint
