name: Renovate

on:
  schedule:
    # Every Monday and Thursday at 7 AM UTC
    - cron: '0 7 * * 1,4'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          private-key: ${{ secrets.GOHFERT_RENOVATOR_APP_PRIVATE_KEY }}
          client-id: ${{ secrets.GOHFERT_RENOVATOR_APP_ID }}
          owner: ${{ github.repository_owner }}
          repositories: 'gohfert-cluster'

      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@22e0a16091fc706b04affe6ae53d5e3358ac4023 # v46.1.19
        with:
          configurationFile: renovator.json
          token: ${{ steps.get_token.outputs.token }}
        env:
          RENOVATE_PLATFORM_COMMIT: 'enabled'
          RENOVATE_REPOSITORIES: 'felix-seifert/gohfert-cluster'
