name: update-cache

on:
  push:
    branches:
      - main

jobs:
  cache-update:
    name: Install requirements and cache them
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # SHA for version 5.0.0

      - name: Prepare environment to ensure cache is updated
        uses: ./.github/actions/prepare-env-composite-action
